<?php
/**
 * Webinse
 *
 * PHP Version 5.6.23
 *
 * @category    Webinse
 * @package     Webinse_Faq3
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * Template for add/edit FAQ item
 *
 * @category    Webinse
 * @package     Webinse_Faq3
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * @var $this Webinse_Faq3_Block_Faq
 */
?>
<?php $helper = Mage::helper('your_helper_name'); // @todo: you must set properly URI of your helper ?>
<?php $item = $this->getFaqById() ?>

<form action="<?php /* @todo link to index controller method save */ ?>" method="post" id="form-validate">
    <h2 class="legend">
        <?php if ($item->getId()): ?>
            <?php echo $helper->__('Edit') ?>
        <?php else: ?>
            <?php echo $helper->__('Add') ?>
        <?php endif; ?>
    </h2>
    <ul class="form-list">
        <?php 
        /**
         * @todo complete form use example
         *       class 'required-entry' means that field is required and js will be check it
         *          you can see all classes in the js/prototype/validation.js (line 418)
         */
        ?>
        <li class="wide">
            <label for="something" class="required"><em>*</em><?php echo $helper->__('something') ?></label>
            <div class="input-box">
                <input type="text" name="something" value="" title="<?php echo $helper->__('something') ?>" class="input-text required-entry" />
            </div>
        </li>
    </ul>
</form>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>


