<?php
/**
 * Webinse
 *
 * PHP Version 5.6.23
 *
 * @category    Webinse
 * @package     Webinse_Faq3
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * Template for view all FAQ
 *
 * @category    Webinse
 * @package     Webinse_Faq3
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * @var $this Webinse_Faq3_Block_Faq
 */
?>
<?php $helper = Mage::helper('your_helper_name'); // @todo: you must set properly URI of your helper ?>
<?php $collection = $this->getAllFaq() ?>

<h1><?php echo $helper->__('Frequently Asked Questions'); ?></h1>
<?php if ($collection->getSize()): ?>

    <?php
    /**
     * @todo Output all faq near each record you must add link to delete and edit it page (use methods deleteAction and editFaqByIdAction)
     */
    ?>

<?php endif; ?>

<?php
/**
 * @todo Add link to 'add new faq' page (use method getUrl)
 */
?>


