<?php
/**
 * Webinse
 *
 * PHP Version 5.6.23
 *
 * @category    Webinse
 * @package     Webinse_Faq3
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * Template for view all FAQ
 *
 * @category    Webinse
 * @package     Webinse_Faq3
 * @author      Webinse Team <info@webinse.com>
 * @copyright   2017 Webinse Ltd. (https://www.webinse.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0
 */
/**
 * @var $this Webinse_Faq3_Block_Faq
 */
?>
<?php $helper = Mage::helper('faq3/data'); // (Done)@todo: you must set properly URI of your helper ?>
<?php $collection = $this->getAllFaq(); ?>

<h1><?php echo $helper->__('Frequently Asked Questions'); ?></h1>
<?php if ($collection->getSize()): ?>

    <?php
    /**
     * @todo Output all faq near each record you must add link to delete and edit it page (use methods deleteAction and editFaqByIdAction)
     */ ?>
    <?php foreach($collection as $item):?>
        <?php $id = $item->getId(); ?>
            <h2>
            <?php echo $item->getQuestion(); ?>
            <?php echo ' <a href="'; ?>
            <?php echo $this->getUrl('faq3/index/addnewfaq/', array(id=>$id)); ?>
            <?php echo '">edit</a> '; ?>
            <?php echo ' <a href="delete/id/' .$item->getId(). '">delete</a>'; ?>
            </h2>
            <p> <?php echo $item->getAnswer(); ?> </p>
            <p> <?php echo $item->getDate(); ?>  </p>
        <hr>
    <?php endforeach; ?>


<?php endif; ?>

<?php
/**
 * @todo Add link to 'add new faq' page (use method getUrl)
 */
?>

<hr>
<?php echo "<a href='"; ?>
<?php echo $this->getUrl('faq3/index/addnewfaq/', array(id=>0)); ?>
<?php echo "'>Add new faq</a>"; ?>




